id: PA1E6F05D
initial_creation_type: input
source_metadata:
  Title: Āryaśālistambakakārikā
  Editor: Rabten, Sonam
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '2004'
  Āryaśālistambakakārikā:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2007'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:52:42.922890'
last_modified_at: '2022-03-08T16:52:42.922898'
